### ISSUE TITLE
Best way to disable highlighting/selecting across the application

### ISSUE THREAD

**Issue by Somiac** [atom/electron#2538]
What is the best way to remove highlighting or allowing users to select text within the app to make it feel more native?

**Comment by OlsonDev** [comment]
I'm not sure if this is the best way, but this is what I do:

    :not(input):not(textarea),
    :not(input):not(textarea)::after,
    :not(input):not(textarea)::before {
        -webkit-user-select: none;
        user-select: none;
        cursor: default;
    }

**Comment by Somiac** [comment]
Best or not, this worked perfectly! Thanks :)

**Comment by OlsonDev** [comment]
You bet :-)

**Comment by OlsonDev** [comment]
@Somiac I just came across another style I needed to add to make my app feel more native and thought you/others may be interested:

```css
a:not([draggable=true]), img:not([draggable=true]) {
    -webkit-user-drag: none;
    user-drag: none; /* Technically not supported in Electron yet */
}
a[href^="http://"],
a[href^="https://"],
a[href^="ftp://"] {
    -webkit-user-drag: auto;
    user-drag: auto; /* Technically not supported in Electron yet */
}
```

Depending on your use-case, you may want to scope it to something like `a.button` instead.

Also note `draggable` is an [enumerated attribute, not a Boolean one](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/draggable), hence `=true` in the selector.

Unfortunately `:local-link` was [removed from the Selectors Level 4 spec](http://css4.rocks/selectors-level-4/local-link-pseudo-class.php) so it looks like the `href` attribute "hack" will be there for a while. :-P
