### ISSUE TITLE
Possible memory leak with remote object in Win 8.1

### ISSUE THREAD

**Issue by JenningsWu** [atom/electron#3934]
Electron version: v0.36.1
OS: Windows 8.1, 64 bit

It seems that there exists a memory leak because of the circular references in remote object, and this issue can be shown in this way:

create a file `test.coffee`:
```
module.exports =
  createObject: () ->
    test = 
      testA: "hello"
      testB: 'test'
      testC:
        aaa: 'aaa'
        bbb: 5
```
then in the devTool's Console of an app, we run
```
var test = remote.require('test.coffee')
var t
for (var i=0; i<200000; i++) {
  t = test.createObject()
}
```
result:
![tm69 vh9f 7j q kz ut yh](https://cloud.githubusercontent.com/assets/6861365/12018806/b69ae3c4-ad1c-11e5-8586-c42aa45be044.png)
![8_p1tuv1 x0uld42fz j f7](https://cloud.githubusercontent.com/assets/6861365/12018816/d7385fe4-ad1c-11e5-9f01-8167248c6434.png)
