### ISSUE TITLE
Choose default fonts for BrowserWindow and webview

### ISSUE THREAD

**Issue by yuya-oc** [atom/electron#4132]
Is there the way to change default fonts?

In my Electron app, webview loads the external URL. Until v0.35.3, Electron had used non-Japanese fonts for Kanji-characters in such as `san-serif` and `monospace` on Windows. So I had added following css by using `webview.insertCSS()` in order to use Japanese fonts. (My environment is Windows 10 Pro 64bit JPN)

```css
@font-face {
  font-family: sans-serif;
  src: local('Meiryo'); /* Default Japanese font for Windows Vista, 7 */
}

@font-face {
  font-family: monospace;
  src: local('MS Gothic'); /* Japanese gothic font for Windows */
}
```

However, the above css has no effects from v0.36.0. `MS Gothic` (I inferred) is used as default fonts on Windows.

So my expecting is one of following:
* The font-face css has effects.
* There is the function to choose default fonts.
