### ISSUE TITLE
"Paused in debugger" buttons unclickable when on top of -webkit-app-region: drag

### ISSUE THREAD

**Issue by OlsonDev** [atom/electron#4137]
I have a `BrowserWindow` with `frame: false` and my own title bar with `-webkit-app-region: drag;`. I put a `debugger;` in a script. Later I didn't need it so I went to click the `Resume script execution (F8)` button but it wasn't clickable... or so I thought. The bottom part was clickable, because it wasn't on top of the draggable area. See below, black pixels = title bar:

![paused-in-debugger-initial](https://cloud.githubusercontent.com/assets/308072/12378252/d6fe4f84-bcfd-11e5-981b-d9f27b630a9b.gif)

Making the draggable area bigger made them completely unclickable:
![paused-in-debugger-larger](https://cloud.githubusercontent.com/assets/308072/12378311/6b5923ec-bcff-11e5-8417-6fb697e85bf5.gif)
You can actually drag the window around with the buttons, too.

Removing the `-webkit-app-region: drag;` "fixes" the issue:
![paused-in-debugger-no-drag](https://cloud.githubusercontent.com/assets/308072/12378317/85db6676-bcff-11e5-823d-5213631dfef8.gif)

**Comment by DerNivel** [comment]
You can resume with a click on the specific button in the DevTools as workaround.

**Comment by OlsonDev** [comment]
Oh, I know, or press F8. Just reporting it's broken as-is.

**Comment by zcbenz** [comment]
When you click on a draggable region, it is impossible for Electron to know whether you are clicking something or dragging the window. This is a limitation of desktop operating systems.

**Comment by OlsonDev** [comment]
I understand that -- I figured the solution would be simply making those buttons `-webkit-app-region: no-drag` like my own custom buttons on top of the title bar are.

**Comment by etiktin** [comment]
@OlsonDev that should work. It's a low priority issue since it's exposed only to the developer and there are simple workarounds, so I guess that's why it's closed as won't fix. That said, if you find the matching css rule and open a PR, it will probably be accepted.

**Comment by OlsonDev** [comment]
I came across [this HTML](https://code.google.com/p/chromium/codesearch#chromium/src/third_party/WebKit/Source/core/inspector/InspectorOverlayPage.html&sq=package:chromium&type=cs&l=1625):
```html
<canvas id="canvas" class="fill"></canvas>
<div id="element-title">
  <span id="tag-name"></span><span id="node-id"></span><span id="class-name"></span>
  <span id="node-width"></span><span class="px">px</span><span class="px"> &#xD7; </span><span id="node-height"></span><span class="px">px</span>
</div>
<div id="tooltip-container"></div>
<div id="editor" class="fill"></div>
<div class="controls-line">
    <div class="message-box"><div id="paused-in-debugger"></div></div>
    <div class="button" id="resume-button" title="Resume script execution (F8)."><div class="glyph"></div></div>
    <div class="button" id="step-over-button" title="Step over next function call (F10)."><div class="glyph"></div></div>
</div>
<div id="log"></div>
```
The relevant CSS is in the same file [here](https://code.google.com/p/chromium/codesearch#chromium/src/third_party/WebKit/Source/core/inspector/InspectorOverlayPage.html&sq=package:chromium&type=cs&l=114) (copy-paste starts a bit above for more context, some noise snipped):
```css
.fill {
    position: absolute;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
}

/* snip */

#canvas, #layout-editor-matched-nodes-canvas {
    pointer-events: none;
}

.controls-line {
    display: flex;
    justify-content: center;
    margin: 10px 0;
}

/* snip */

.controls-line .button {
    width: 26px;
    margin-left: -1px;
    margin-right: 0;
    padding: 0;
}

/* snip */

#resume-button .glyph {
    /* -webkit-mask-image: snip */
    -webkit-mask-size: 13px 10px;
    background-color: rgb(66, 129, 235);
}

#step-over-button .glyph {
    /* -webkit-mask-image: snip */
    -webkit-mask-size: 18px 10px;
}
```

@etiktin Did you mean open a PR here or with Chromium? ... I'd really rather not set up a Chromium environment to test adding `.controls-line { -webkit-app-region: no-drag; }` ... I'd have no idea what I'm doing.
