### ISSUE TITLE
Unable to use CSSVariables

### ISSUE THREAD

**Issue by tundrax** [atom/electron#4337]
Need help. I've been trying to use css variables with `v0.36.7`, no luck yet.
```js
webPreferences: {
  blinkFeatures: 'CSSVariables'
}
```
```css
:root {
  --primary-color: #5E35B1;
}

body {
  background-color: var(--primary-color, #FF0000);
}
```
